"""add backup schedule

Revision ID: 020fe06cd293
Revises: 2f96a70abba6
Create Date: 2025-08-02 13:45:56.145658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020fe06cd293'
down_revision: Union[str, None] = '2f96a70abba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_schedule_id'), 'backup_schedule', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_schedule_id'), table_name='backup_schedule')
    op.drop_table('backup_schedule')
    # ### end Alembic commands ###
