"""add mfa_secret and mfa_sessions

Revision ID: 0fa7fbf7423e
Revises: a9deee19e45e
Create Date: 2025-08-09 22:01:03.244281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fa7fbf7423e'
down_revision: Union[str, None] = 'a9deee19e45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfa_sessions', sa.Column('secret', sa.String(), nullable=False))
    op.add_column('mfa_sessions', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('mfa_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_mfa_sessions_token', table_name='mfa_sessions')
    op.create_index(op.f('ix_mfa_sessions_id'), 'mfa_sessions', ['id'], unique=False)
    op.drop_column('mfa_sessions', 'user_agent')
    op.drop_column('mfa_sessions', 'used')
    op.drop_column('mfa_sessions', 'token')
    op.drop_column('mfa_sessions', 'expires_at')
    op.drop_column('mfa_sessions', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mfa_sessions', sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mfa_sessions', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mfa_sessions', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mfa_sessions', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mfa_sessions', sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mfa_sessions_id'), table_name='mfa_sessions')
    op.create_index('ix_mfa_sessions_token', 'mfa_sessions', ['token'], unique=True)
    op.alter_column('mfa_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('mfa_sessions', 'is_verified')
    op.drop_column('mfa_sessions', 'secret')
    # ### end Alembic commands ###
