"""add security question

Revision ID: 68174604a418
Revises: 7c5e31b93567
Create Date: 2025-08-13 22:35:58.264186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68174604a418'
down_revision: Union[str, None] = '7c5e31b93567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('security_question', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('security_answer', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'security_answer')
    op.drop_column('user', 'security_question')
    # ### end Alembic commands ###
