"""Add MFA columns

Revision ID: 7c5e31b93567
Revises: 0fa7fbf7423e
Create Date: 2025-08-09 23:55:11.361052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5e31b93567'
down_revision: Union[str, None] = '0fa7fbf7423e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('requires_mfa_setup', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('failed_login_count', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('mfa_backup_codes', sa.Text(), nullable=True))
    op.drop_column('user', 'mfa_forced')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mfa_forced', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'mfa_backup_codes')
    op.drop_column('user', 'failed_login_count')
    op.drop_column('user', 'requires_mfa_setup')
    # ### end Alembic commands ###
