"""add mfa_secret and mfa_sessions

Revision ID: a9deee19e45e
Revises: 020fe06cd293
Create Date: 2025-08-09 21:50:59.529891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9deee19e45e'
down_revision: Union[str, None] = '020fe06cd293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfa_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_sessions_token'), 'mfa_sessions', ['token'], unique=True)
    op.add_column('user', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('user', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('mfa_forced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mfa_forced')
    op.drop_column('user', 'mfa_enabled')
    op.drop_column('user', 'mfa_secret')
    op.drop_index(op.f('ix_mfa_sessions_token'), table_name='mfa_sessions')
    op.drop_table('mfa_sessions')
    # ### end Alembic commands ###
